### ISSUE TITLE
City selection: porteuges version

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-city-selection-scrolly-portuguese#1]
⭐ Review Link: https://dashing-choux-141b02.netlify.app/?review=true 
 
## Action Items

- [x] set up GA tag
- [x] embed GA tag
- [x] transalte ocmponets to portegues
- [x] set up sueprflow project
- [x] embed superflow project
- [x] deploy review
- [x] review with BR team under email title 'SALURBAL city-selection feedback requested'
- [x] make updates
- [x] check over with @Nat325 
- [ ] deploy production: https://drexel-uhc.github.io/salurbal-city-selection-scrolly-portuguese/

**Comment by ran-codes** [comment]
@usamabilal The porteugues version of city selection is ready for review. Link: https://dashing-choux-141b02.netlify.app/?review=true

**Comment by ran-codes** [comment]
- [x] update head metadata in all scrollies 

![image](https://github.com/Drexel-UHC/salurbal-city-selection-scrolly-portuguese/assets/45013044/a06c8822-926d-4ef3-82f1-6b295dd0f1a0)

**Comment by ran-codes** [comment]
@Nat325 

- **Review link:** https://dashing-choux-141b02.netlify.app/?review=true
- **Feedback via superflow**  can make comments directly on that page with super flow the tool you see on the bottom right. you may need to sign up with a gmail. The UI should be intuitive enough to use but to be safe here is a [video intro to how to use superflow for feedback.](https://www.youtube.com/watch?v=zyhgNKGuPLc&ab_channel=Superflow%3ASwiftestcollaborationtool)

**Comment by ran-codes** [comment]
Thanks @Nat325. @usama just two minor edits from @Nat325 in the [review version]( https://dashing-choux-141b02.netlify.app/?review=true). Do you want to take a look before i update and deploy then close issue?

**Comment by usamabilal** [comment]
Perfect! address those two and we're good to go! thanks @Nat325 for the final review.
One thing: i'd like to add an extra line (after engineered) along the lines of "Translation to portuguese supported by: Uriel Moreira Silva, Sol Carnavalli Rocha, and Natalie Rodrigues"
@Nat325 , what would be a good way of phrasing this?

@ran-codes , i'm adding a similar one to the spanish repo

**Comment by ran-codes** [comment]
Updated: https://dashing-choux-141b02.netlify.app/?review=true

Pending @Nat325 review of new acknowledgement: `Tradução para o português apoiada por: Silva Sol, Carnavalli Rocha e Natalie Rodrigues`  .

**Comment by usamabilal** [comment]
I think chat gpt translated some of Uriels name?
________________________________

**Comment by ran-codes** [comment]
**Updates**

 - [x] Fixed Uriels name
 - [x] reviewed acknowledgment section translation with Nat
 - [x] deployed to production: https://drexel-uhc.github.io/salurbal-city-selection-scrolly-portuguese/
